# Generated by Django 4.2 on 2023-04-27 22:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jokes", "0002_alter_joke_date_published"),
    ]

    operations = [
        migrations.RenameField(
            model_name="joke",
            old_name="laughs",
            new_name="laughed_at_by",
        ),
    ]
